pycards/models.py
import sqlite3
from flask import g, current_app
from contextlib import contextmanager
from datetime import datetime

TODAY_STR = datetime.today().strftime("%Y-%m-%d")


def get_db():
    db = getattr(g, "_database", None)
    if db is None:
        db_name = current_app.config["DATABASE"]
        g._database = sqlite3.connect(db_name)
        db = g._database
    return db


@contextmanager
def get_db_connection():
    db = get_db()
    try:
        yield db
    except Exception as e:
        print("Error",e)
    finally:
        db.close()


def init_db():
    db = get_db()
    with current_app.open_resource("schema.sql", mode="r") as f:
        db.cursor().executescript(f.read())
    db.commit()

pycards/__init__.py
# from .app import app as myapp
# from .models import init_db

# __all__ = ["myapp"]

# if __name__ == '__main__':
#     print("Initializing database...")
#     init_db()
#     print("Database initialized.")
#     myapp.run(debug=True)

from .app import app ,main

__all__ = ["app","main"]

# def main():
#     print("Initializing database...")
#     init_db()
#     print("Database initialized.")
#     myapp.run(debug=True)

if __name__ == '__main__':
    main()

pycards/app.py
from flask import Flask

from pycards.models import init_db
from .config import Config
from .routes.home import home_bp
from .routes.sentence import sentence_bp
from .routes.word import word_bp

app = Flask(__name__)
app.config.from_object(Config)
# Register blueprints
app.register_blueprint(home_bp)
app.register_blueprint(sentence_bp)
app.register_blueprint(word_bp)


def main():
    with app.app_context():
        init_db()
    app.run(debug=True)


if __name__ == "__main__":
    main()

pycards/routes/home.py
from flask import Blueprint, request, redirect, url_for, render_template
from ..models import get_db_connection, TODAY_STR

from ..language import english

home_bp = Blueprint("main", __name__)
# TODAY_STR= date.strftime("%Y-%m-%d")


@home_bp.route("/")
def home():
    sentences = []
    with get_db_connection() as db:
        cur = db.execute(
            f"""SELECT sentences.id,sentences.content,sentences.descriptions FROM sentences left join words on sentences.id = words.sentence_id
                    where create_date >= '{TODAY_STR}'    or words.sentence_id is NULL
                order by sentences.id desc"""
        )
        sentences = cur.fetchall()
        sentences = [english.parse_sentence(row) for row in sentences]
    return render_template("home.html", sentences=sentences)


@home_bp.route("/submit", methods=["POST"])
def submit():
    sentence = request.form["sentence"]
    descriptions = request.form["descriptions"]

    if sentence:
        with get_db_connection() as db:
            db.execute(
                "INSERT INTO sentences (content,descriptions) VALUES (?,?)",
                [sentence, descriptions],
            )
            db.commit()
    return redirect(url_for("main.home"))

pycards/routes/sentence.py
from flask import Blueprint, jsonify, redirect, request, url_for, render_template

from ..models import get_db_connection, TODAY_STR
from ..language import english

sentence_bp = Blueprint("sentence", __name__, url_prefix="/sentence")


@sentence_bp.route("/manage")
def manage_sentences():
    with get_db_connection() as conn:
        sentences = conn.execute(
            f"SELECT id,content,descriptions FROM sentences  order by id desc limit 20"
        ).fetchall()
        conn.close()
        sentences = [
            english.DBSentence(sentence_id=row[0], content=row[1], descriptions=row[2])
            for row in sentences
        ]
        return render_template("manage_sentences.html", sentences=sentences)


@sentence_bp.route("/delete/<int:sentence_id>")
def delete_sentence(sentence_id):
    with get_db_connection() as db:
        db.execute("DELETE FROM sentences WHERE id = ?", (sentence_id,))
        db.commit()
        return redirect(url_for("sentence.manage_sentences"))


@sentence_bp.route("/submit", methods=["POST"])
def submit_json():
    data = request.get_json()
    sentence = data.get("sentence")
    descriptions = data.get("descriptions")

    if sentence:
        with get_db_connection() as db:
            db.execute(
                "INSERT INTO sentences (content,descriptions) VALUES (?,?)",
                [sentence, descriptions],
            )
            db.commit()
        return jsonify({"status": "success"}), 200
    else:
        return jsonify({"status": "error", "message": "Sentence is required"}), 400

pycards/routes/word.py
from flask import Blueprint, request, redirect, url_for, render_template

from ..models import get_db_connection, TODAY_STR
from ..language import english

word_bp = Blueprint("word", __name__, url_prefix="/word")


@word_bp.route("/submit_word", methods=["POST"])
def submit_word():
    selected_word = request.form["selectedWord"]
    word_definition = request.form["wordDefinition"]
    sentence_id = request.form["sentenceId"]
    if selected_word and word_definition and sentence_id:
        with get_db_connection() as db:
            db.execute(
                "INSERT INTO words (word, definition, sentence_id) VALUES (?, ?, ?)",
                [selected_word, word_definition, sentence_id],
            )
            db.commit()
    return redirect(url_for("main.home"))


@word_bp.route("/query/en")
def query_word():
    word = request.args.get("word")
    if word is None:
        return "No word provided"
    return english.mdict.lookup(word)


@word_bp.route("/query/<path:path>")
def get_resource(path):
    return english.mdict.lookup(path)


def emphasize_word(word_attrs):
    # id,word,content,definition,description
    id = word_attrs[0]
    word = word_attrs[1]
    content: str = word_attrs[2]
    definition = word_attrs[3]
    description = word_attrs[4]

    if content is not None:
        content = content.replace(word, f"<b>{word}</b>")
    return (id, word, content, definition, description)


@word_bp.route("/words")
def show_words():
    with get_db_connection() as db:
        sql = f"""SELECT words.id,words.word,sentences.content, definition,sentences.descriptions 
            FROM words  LEFT JOIN sentences  ON words.sentence_id = sentences.id 
            where sentences.create_date>= '{TODAY_STR}' 
            order by words.id desc"""
        # breakpoint()
        cur = db.execute(sql)
        words = cur.fetchall()
        words = [emphasize_word(word) for word in words]
        return render_template("words.html", words=words)


@word_bp.route("/delete_word/<int:word_id>", methods=["GET"])
def delete_word(word_id):
    with get_db_connection() as db:
        db.execute("DELETE FROM words WHERE id = ?", (word_id,))
        db.commit()
        # conn.close()
        return redirect(url_for("word.show_words"))

pycards/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>Save Sentence</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}" />

</head>

<body>
  <div id="main-view">
    <div class="header">
      <nav>
        <ul>
          <li><a href="{{ url_for('main.home') }}">Home</a></li>
          <li><a href="{{ url_for('sentence.manage_sentences') }}">Manage Sentences</a></li>
          <li><a href="{{ url_for('word.show_words') }}">Word List</a></li>
        </ul>
      </nav>
    </div>
    <div class="container">
      <div class="left">
        <div id="sentence-form">
          <form action="{{ url_for('main.submit') }}" method="post">
            <textarea name="sentence" rows="5" cols="80"></textarea><br />
            <div>
              <textarea id="description" name="descriptions" rows="3" cols="50"></textarea>
              <input type="checkbox" name="keep_description" id="keep_description" {% if
                request.form.get('keep_description') %}checked{% endif %} />
              <label for="keep_description">keep</label>
            </div>
            <input type="submit" value="Submit" />
          </form>
          <div id="sentence-list">

            <ul>
              {% for sentence in sentences %}
              <li class="submitted-sentence" title="{{ sentence.descriptions }}"
                data-sentence-id="{{ sentence.sentence_id }}">{% include "single_sentence.html" %}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="right">
        <div class="top">
          <div>
            <h2>Word</h2>
            <div>
              <form id="wordForm" action="{{ url_for('word.submit_word') }}" method="post">
                <!-- <label for="selectedWord">Selected Word:</label> -->
                <input type="text" id="selectedWord" name="selectedWord" readonly
                  style="margin-bottom: 10px; color: slategray;" /><br />
                <label for="wordDefinition">Definition:</label>
                <textarea id="wordDefinition" name="wordDefinition" rows="4"
                  style="margin-bottom: 10px; padding: 5px; width: 100%;"></textarea><br />
                <input type="hidden" id="sentenceId" name="sentenceId" />
                <input type="submit" value="Submit" style="padding: 5px 10px;" />
              </form>
            </div>
          </div>
        </div>
        <div class="bottom">
          <iframe id="wordIframe" src=""></iframe>
        </div>
      </div>
    </div>
    <script>
      document.addEventListener("DOMContentLoaded", (event) => {
        let localStorageKey = "mydescription"
        let desc = localStorage.getItem(localStorageKey) || '';
        document.getElementById("description").value = desc;
        if (desc !== "") {
          document.getElementById("keep_description").checked = true;
        }
        document.getElementById("sentence-form").addEventListener("submit", (e) => {
          if (!document.getElementById("keep_description").checked) {
            console.log("remove mydescription");
            localStorage.removeItem(localStorageKey);
          } else {
            let desc = document.getElementById("description").value;
            console.log("update mydescription", desc);
            localStorage.setItem(localStorageKey, desc);
          }
        });
        document.querySelectorAll("span.word").forEach(function (span) {
          span.addEventListener("click", function () {
            document.getElementById("selectedWord").value = this.textContent;
            const lemma = this.getAttribute("data-lemma");
            const sentenceId = this.closest("li").getAttribute("data-sentence-id");
            document.getElementById("sentenceId").value = sentenceId;
            document.getElementById("wordIframe").src = `/word/query/en?word=${lemma}`;
          });
        });

      });


    </script>
</body>

</html>

pycards/templates/manage_sentences.html
<!-- manage_sentences.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Manage Sentences</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='table.css') }}" />
  </head>
  <body>
    <div class="container">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Sentence</th>
            <th>Descriptions</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for sentence in sentences %}
          <tr>
            <td>{{ sentence.sentence_id }}</td>
            <td>{{ sentence.content}}</td>
            <td>{{ sentence.descriptions }}</td>
            <td>
              <a href="{{ url_for('sentence.delete_sentence', sentence_id=sentence.sentence_id) }}">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <a href="{{ url_for('main.home') }}">Back to Home</a>
  </body>
</html>

pycards/templates/sentences.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Saved sentences</title>
  </head>
  <body>
    <h1>Saved sentences</h1>
    <ul>
      {% for sentence in sentences %}
      <li>
      {% include "single_sentence.html" %}
      {% endfor %}
      </li>
    </ul>
    <br />
    <a href="{{ url_for('main.home') }}">Back to Home</a>
  </body>
</html>

pycards/templates/single_sentence.html
  <!-- {% set sentence_id = sentence.id %} -->
  {% for word in sentence.words %}
  <span class="word"  data-lemma="{{ word.lemma }}">{{ word.text }}</span>
  {% endfor %}

pycards/templates/words.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Word List</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='table.css') }}"
    />
  </head>
  <body>
    <div class="container">
      <table>
        <thead>
          <tr>
            <th>Word</th>
            <th>Sentence</th>
            <th>Definition</th>
            <th>Description</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for id,word, sentence,definition,description in words %}
          <tr>
            <td>{{ word }}</td>
            <td>{{ sentence |safe }}</td>
            <td>{{ definition }}</td>
            <td>{{ description}}</td>
            <td>
              <a href="{{ url_for('word.delete_word', word_id=id) }}">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <a href="{{ url_for('main.home') }}">Back to Home</a>
  </body>
</html>